blank_issues_enabled: true
contact_links:
  - name: Ask a question
    about: |
      You've come to seek help or want to discuss something related to warp-cors.
    url: https://github.com/bassetts/warp-cors/discussions/new
